version: "3.8"

services:

  configserver:
    image: dewacoding/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - dewacoding
      
  accounts:
    image: dewacoding/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - dewacoding
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 360s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
  
  loans:
    image: dewacoding/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - dewacoding
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 360s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    
  cards:
    image: dewacoding/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - dewacoding
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 360s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      
networks:
  dewacoding: